//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int TransactionID { get; set; }
        public Nullable<int> GameID { get; set; }
        public Nullable<int> SellerID { get; set; }
        public Nullable<int> BuyerID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<decimal> PricePaid { get; set; }
    
        public virtual Buyers Buyers { get; set; }
        public virtual Games Games { get; set; }
        public virtual Sellers Sellers { get; set; }
    }
}
